import = ["/home/rahul/.config/alacritty/env.toml", "/home/rahul/.config/alacritty/colors/falcon.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 7

[window]
opacity = 0.83
